# Generated by Django 5.2.5 on 2025-11-05 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(help_text='Vehicle manufacturer (e.g., Ford, Toyota)', max_length=50)),
                ('model', models.CharField(help_text='Vehicle model (e.g., Transit, Hiace)', max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Manufacturing year')),
                ('vin', models.CharField(help_text='Vehicle Identification Number', max_length=17, unique=True)),
                ('capacity', models.PositiveIntegerField(help_text='Vehicle load capacity')),
                ('capacity_unit', models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', help_text='Unit of measurement for capacity', max_length=2)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address_unit', models.CharField(blank=True, help_text='Unit/Apartment number', max_length=20, null=True)),
                ('address_street', models.CharField(blank=True, help_text='Street address', max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, help_text='City', max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, help_text='State/Province', max_length=100, null=True)),
                ('address_postal_code', models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True)),
                ('address_country', models.CharField(choices=[('CA', 'Canada'), ('US', 'United States')], default='US', help_text='Country', max_length=2)),
                ('address', models.TextField(blank=True, help_text='Legacy combined address field', null=True)),
                ('company_name', models.CharField(blank=True, help_text='Optional company name', max_length=255, null=True)),
                ('is_business', models.BooleanField(default=False, help_text='Is this a business customer?')),
                ('preferred_pickup_address', models.TextField(blank=True, help_text='Default pickup address if different from main address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.TextField()),
                ('dropoff_location', models.TextField()),
                ('same_pickup_as_customer', models.BooleanField(default=False, help_text="Use customer's main address as pickup location")),
                ('use_preferred_pickup', models.BooleanField(default=False, help_text="Use customer's preferred pickup address")),
                ('same_dropoff_as_customer', models.BooleanField(default=False, help_text="Use customer's main address as dropoff location")),
                ('item_description', models.CharField(default='Pending', help_text='Describe the item to be picked up (e.g. TV, sofa, furniture)', max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('En Route', 'En Route'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('special_instructions', models.TextField(blank=True, help_text='Special delivery instructions', null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated delivery cost', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='delivery.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.vehicle')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_from', models.DateField()),
                ('assigned_to', models.DateField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.vehicle')),
            ],
            options={
                'ordering': ['-assigned_from'],
                'unique_together': {('driver', 'vehicle', 'assigned_from')},
            },
        ),
    ]
