# CIO DIRECTIVE: Fix Driver One-To-One User Relationship - Zero Nulls
# Generated by Django 5.2.5 on 2025-11-22 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import random
import string


def create_user_accounts_for_drivers(apps, schema_editor):
    """
    CIO DIRECTIVE: Create User accounts for all drivers with NULL user_id
    Populate first_name, last_name from existing name field
    """
    Driver = apps.get_model('delivery', 'Driver')
    User = apps.get_model('auth', 'User')
    
    # Find all drivers without user accounts
    drivers_without_users = Driver.objects.filter(user__isnull=True)
    
    print(f"CIO DIRECTIVE: Creating User accounts for {drivers_without_users.count()} legacy drivers")
    
    for driver in drivers_without_users:
        # Split name into first_name and last_name
        name_parts = driver.name.split(' ', 1)
        first_name = name_parts[0] if name_parts else 'Driver'
        last_name = name_parts[1] if len(name_parts) > 1 else f'{driver.id}'
        
        # Generate unique username
        base_username = f"{first_name.lower()}.{last_name.lower()}".replace(' ', '')
        username = base_username
        counter = 1
        while User.objects.filter(username=username).exists():
            # Add random 4-digit suffix for conflicts
            random_suffix = ''.join(random.choices(string.digits, k=4))
            username = f"{base_username}{random_suffix}"
            counter += 1
            if counter > 10:  # Prevent infinite loop
                username = f"driver{driver.id}_{random_suffix}"
                break
        
        # Create User account
        user = User.objects.create(
            username=username,
            first_name=first_name,
            last_name=last_name,
            email=f"{username}@deliveryapp.temp",  # Temporary email
            is_active=driver.active
        )
        
        # Link driver to user
        driver.user = user
        driver.first_name = first_name
        driver.last_name = last_name
        driver.save()
        
        print(f"  Created User '{username}' for Driver '{driver.name}' (ID: {driver.id})")
    
    print(f"CIO DIRECTIVE: Successfully created {drivers_without_users.count()} User accounts")


def reverse_user_accounts_for_drivers(apps, schema_editor):
    """
    Reverse migration: Delete created User accounts and clear driver relationships
    """
    Driver = apps.get_model('delivery', 'Driver')
    User = apps.get_model('auth', 'User')
    
    # Find all drivers with temp email users (created by this migration)
    temp_users = User.objects.filter(email__endswith='@deliveryapp.temp')
    driver_count = Driver.objects.filter(user__in=temp_users).count()
    
    print(f"Reversing CIO directive: Removing {temp_users.count()} User accounts for {driver_count} drivers")
    
    # Clear driver user relationships first
    Driver.objects.filter(user__in=temp_users).update(user=None, first_name='', last_name='')
    
    # Delete the temporary User accounts
    temp_users.delete()
    
    print(f"Reversed: Removed User accounts and cleared driver relationships")


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Step 1: Add new fields (nullable initially)
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(blank=True, help_text='Driver first name', max_length=150),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(blank=True, help_text='Driver last name', max_length=150),
        ),
        
        # Step 2: Make name field optional (deprecated)
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use user.first_name + user.last_name', max_length=255),
        ),
        
        # Step 3: Create User accounts for drivers with NULL user_id
        migrations.RunPython(
            create_user_accounts_for_drivers,
            reverse_user_accounts_for_drivers
        ),
        
        # Step 4: Update user field to be non-nullable with PROTECT
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        
        # Step 5: Add database constraint to prevent NULL user_id
        migrations.AddConstraint(
            model_name='driver',
            constraint=models.CheckConstraint(condition=models.Q(('user__isnull', False)), name='driver_must_have_user'),
        ),
    ]
