# Generated by Django 5.2.5 on 2025-09-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_delivery_delivery_date_delivery_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='item_description',
            field=models.CharField(default='Pending', help_text='Describe the item to be picked up (e.g. TV, sofa, furniture)', max_length=255),
        ),
    ]
