# Generated by Django 5.2.5 on 2025-12-04 21:48
# CIO DIRECTIVE NOV 24 2025 — Remove deprecated name column — replaced by first_name/last_name + User model

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_cio_directive_fix_driver_user_relationship'),
    ]

    operations = [
        # CIO DIRECTIVE: Remove deprecated 'name' column from delivery_driver table
        # Data is preserved via first_name/last_name fields linked to User model
        migrations.RemoveField(
            model_name='driver',
            name='name',
        ),
    ]
