# Generated by Django 5.2.5 on 2026-06-12 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_deprecated_name_column_cio_directive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DRIVER_LICENSE', 'Driver license'), ('VEHICLE_REGISTRATION', 'Vehicle registration'), ('COMMERCIAL_INSURANCE', 'Commercial insurance'), ('INSPECTION', 'Inspection')], max_length=32)),
                ('policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issuer', models.CharField(blank=True, help_text='Carrier, DMV, etc.', max_length=255, null=True)),
                ('coverage_type', models.CharField(blank=True, choices=[('COMMERCIAL', 'Commercial'), ('PERSONAL', 'Personal'), ('OTHER', 'Other')], help_text='Insurance documents only', max_length=16, null=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('file_key', models.CharField(blank=True, help_text='Private storage object key (S3) after presigned upload', max_length=512, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='delivery.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='delivery.vehicle')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_legal_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_type', 'status'], name='delivery_le_documen_9a8514_idx'), models.Index(fields=['vehicle', 'document_type', 'status'], name='delivery_le_vehicle_42bb2e_idx'), models.Index(fields=['driver', 'document_type', 'status'], name='delivery_le_driver__c919ce_idx')],
            },
        ),
    ]
