# Generated by Django 5.2.5 on 2025-09-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity_unit',
            field=models.CharField(choices=[('kg', 'Kilograms'), ('lb', 'Pounds')], default='kg', help_text='Unit of measurement for capacity', max_length=2),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(help_text='Vehicle load capacity'),
        ),
    ]
