# Generated by Django 5.2.5 on 2025-09-23 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_vehicle_capacity_unit_alter_vehicle_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='delivery',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated delivery cost', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Special delivery instructions', null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='use_preferred_pickup',
            field=models.BooleanField(default=False, help_text="Use customer's preferred pickup address"),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='same_pickup_as_customer',
            field=models.BooleanField(default=False, help_text="Use customer's main address as pickup location"),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('company_name', models.CharField(blank=True, help_text='Optional company name', max_length=255, null=True)),
                ('is_business', models.BooleanField(default=False, help_text='Is this a business customer?')),
                ('preferred_pickup_address', models.TextField(blank=True, help_text='Default pickup address if different from main address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='delivery.customer'),
        ),
    ]
