# Generated by Django 5.2.5 on 2026-07-19 18:27

import django.db.models.deletion
from django.db import migrations, models


def seed_vehicle_catalog(apps, schema_editor):
    from delivery.vehicle_catalog_data import VEHICLE_CATALOG_ENTRIES

    VehicleManufacturer = apps.get_model('delivery', 'VehicleManufacturer')
    VehicleModelSpec = apps.get_model('delivery', 'VehicleModelSpec')

    manufacturers = {}
    for entry in VEHICLE_CATALOG_ENTRIES:
        name = entry['manufacturer']
        if name not in manufacturers:
            manufacturers[name], _ = VehicleManufacturer.objects.get_or_create(name=name)

        VehicleModelSpec.objects.update_or_create(
            manufacturer=manufacturers[name],
            name=entry['model'],
            start_year=entry['start_year'],
            defaults={
                'end_year': entry['end_year'],
                'max_payload_lb': entry['max_payload_lb'],
                'max_towing_lb': entry['max_towing_lb'],
                'notes': entry['notes'],
                'is_active': True,
            },
        )


def unseed_vehicle_catalog(apps, schema_editor):
    VehicleModelSpec = apps.get_model('delivery', 'VehicleModelSpec')
    VehicleManufacturer = apps.get_model('delivery', 'VehicleManufacturer')
    VehicleModelSpec.objects.all().delete()
    VehicleManufacturer.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_driver_license_issuing_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModelSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Null means still in production.', null=True)),
                ('max_payload_lb', models.PositiveIntegerField(help_text='Approximate maximum factory payload rating (lb).')),
                ('max_towing_lb', models.PositiveIntegerField(help_text='Approximate maximum factory towing rating (lb).')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='model_specs', to='delivery.vehiclemanufacturer')),
            ],
            options={
                'verbose_name': 'vehicle model spec',
                'verbose_name_plural': 'vehicle model specs',
                'ordering': ['manufacturer__name', 'name', 'start_year'],
                'unique_together': {('manufacturer', 'name', 'start_year')},
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_spec',
            field=models.ForeignKey(blank=True, help_text='Catalog reference for make/model and official payload limits.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='delivery.vehiclemodelspec'),
        ),
        migrations.RunPython(seed_vehicle_catalog, unseed_vehicle_catalog),
    ]
