# Generated by Django 5.2.5 on 2025-09-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_driver_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='same_dropoff_as_customer',
            field=models.BooleanField(default=False, help_text="Use customer's main address as dropoff location"),
        ),
    ]
