# Generated by Django 5.2.5 on 2025-09-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_delivery_same_dropoff_as_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='deliveryassignment',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-id']},
        ),
    ]
