# Generated by Django 5.2.5 on 2025-10-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0009_alter_customer_options_alter_delivery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_postal_code',
            field=models.CharField(blank=True, help_text='Postal/ZIP code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_street',
            field=models.CharField(blank=True, help_text='Street address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address_unit',
            field=models.CharField(blank=True, help_text='Unit/Apartment number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text='Legacy combined address field', null=True),
        ),
    ]
