# Generated by Django 5.2.5 on 2026-08-13 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_staff_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    StaffProfile = apps.get_model('delivery', 'StaffProfile')
    for user in User.objects.filter(is_staff=True):
        StaffProfile.objects.get_or_create(
            user_id=user.id,
            defaults={'staff_role': 'super_admin'},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_driver_address_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_role', models.CharField(choices=[('super_admin', 'Super Admin'), ('operations_admin', 'Operations Admin'), ('compliance_reviewer', 'Compliance Reviewer'), ('read_only', 'Read Only')], default='super_admin', max_length=32)),
                ('job_title', models.CharField(blank=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.RunPython(backfill_staff_profiles, migrations.RunPython.noop),
    ]
