# Generated by Django 5.2.5 on 2025-10-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0010_customer_address_city_customer_address_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_country',
            field=models.CharField(choices=[('CA', 'Canada'), ('US', 'United States')], default='US', help_text='Country', max_length=2),
        ),
    ]
