# Generated by Django 5.2.5 on 2025-10-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0011_customer_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(blank=True, help_text='Vehicle manufacturer (e.g., Ford, Toyota)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Manufacturing year', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, help_text='Vehicle model (e.g., Transit, Hiace)', max_length=50, null=True),
        ),
    ]
