# Generated by Django 5.2.5 on 2025-11-20 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_address', models.TextField(help_text='Original address as entered by user')),
                ('unit', models.CharField(blank=True, help_text='Unit/Apartment number', max_length=50, null=True)),
                ('street_number', models.CharField(blank=True, help_text='Street number', max_length=20, null=True)),
                ('street_name', models.CharField(blank=True, help_text='Street name', max_length=255, null=True)),
                ('street_type', models.CharField(blank=True, help_text='Street type (St, Ave, Rd, etc.)', max_length=50, null=True)),
                ('city', models.CharField(blank=True, help_text='City name', max_length=100, null=True)),
                ('state_province', models.CharField(blank=True, help_text='State or Province', max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, help_text='Postal or ZIP code', max_length=20, null=True)),
                ('country', models.CharField(blank=True, help_text='Country', max_length=50, null=True)),
                ('normalized_address', models.TextField(blank=True, help_text='Normalized full address', null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending Validation'), ('valid', 'Valid Address'), ('invalid', 'Invalid Address'), ('partial', 'Partially Valid')], default='pending', max_length=20)),
                ('validation_source', models.CharField(choices=[('google', 'Google Maps API'), ('canada_post', 'Canada Post API'), ('manual', 'Manual Entry'), ('usaddress', 'US Address Parser')], default='manual', max_length=20)),
                ('confidence_score', models.FloatField(blank=True, help_text='Validation confidence score (0.0 - 1.0)', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='Latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='Longitude coordinate', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_by', models.ForeignKey(blank=True, help_text='User who validated this address', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AddressValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_source', models.CharField(choices=[('google', 'Google Maps API'), ('canada_post', 'Canada Post API'), ('manual', 'Manual Entry'), ('usaddress', 'US Address Parser')], max_length=20)),
                ('request_data', models.JSONField(help_text='API request data')),
                ('response_data', models.JSONField(help_text='API response data')),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time', models.FloatField(help_text='Processing time in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_logs', to='address_validation.validatedaddress')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='validatedaddress',
            index=models.Index(fields=['validation_status'], name='address_val_validat_571071_idx'),
        ),
        migrations.AddIndex(
            model_name='validatedaddress',
            index=models.Index(fields=['postal_code'], name='address_val_postal__fe0527_idx'),
        ),
        migrations.AddIndex(
            model_name='validatedaddress',
            index=models.Index(fields=['city', 'state_province'], name='address_val_city_d23dc6_idx'),
        ),
    ]
